# Generated by Django 4.2.6 on 2023-11-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=150, verbose_name="место")),
                ("time", models.TimeField(verbose_name="время")),
                ("action", models.CharField(max_length=300, verbose_name="действие")),
                (
                    "pleasant_habit",
                    models.BooleanField(verbose_name="признак приятной привычки"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("1", "1 раз в день"),
                            ("2", "1 раз в 2 дня"),
                            ("3", "1 раз в 3 дня"),
                            ("4", "1 раз в 4 дня"),
                            ("5", "1 раз в 5 дней"),
                            ("6", "1 раз в 6 дней"),
                            ("7", "1 раз в 7 дней"),
                        ],
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(verbose_name="время на выполнение"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="признак публикации"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "полезная привычка",
                "verbose_name_plural": "полезные привычки",
            },
        ),
    ]
